Styling
Ochiengsteven/bookstore pull request #5
Opened 2023-08-25 12:33 UTC by Ochiengsteven

✨ **Enhancement: Finalizing Design to Match Zeplin's Specifications**

This pull request marks the completion of design enhancements, focusing on aligning the application's visual elements with the design specifications provided by `Zeplin`. The main objective is to integrate any missing JSX elements and apply styling according to the CSS rules outlined in **`Zeplin`**.

### **Changes Made:**

- Added any missing **JSX** elements to the application's components as required.
- Adjusted styling attributes based on the CSS rules from Zeplin's design specifications.

### **Design Consistency:**

- Ensured the application's appearance matches the design defined in Zeplin.
- Verified that all elements, including their positions, sizes, and styling, adhere to the provided design guidelines.

**Note:**

- No additional functionality was added during this phase; the primary focus was on design consistency.

> By meticulously integrating the necessary JSX elements and meticulously adhering to Zeplin's design guidelines, this PR finalizes the design of the application, ensuring that its visual presentation is consistent and aligned with the specified design specifications.

🎨 Please review and authorize merge to bring the application's design in line with Zeplin's standards!

2023-08-25 13:25 UTC, Reem-lab requested changes
# Hi @Ochiengsteven, 👋🏻👋🏻

Great job so far! ✨⭐🤩✅
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>


## Highlights
- [ ] No linters error ✅
- [ ] Followed Gitflow ⭐
- [ ] Great job working on the functionality on the styles🔥
- [ ] Descriptive PR 🚀

## Required Changes ♻️
_Check the comments under the review._
- [ ] In general, I think you should change the font type in all the project you can take the information of the type and  colors from the Zeplin


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 13:25 UTC, Reem-lab commented on src/components/BookForm.js
> +            onChange={(e) => setAuthor(e.target.value)}
- [ ] Great job working on the styles so far but I think it would be great if you fix some issues here since I think in this part the spaces are different than the given design In [Zeplin](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378) so kindly make it smaller to match the given design ⬇🔥🚀🤩

- [ ] I think it would be great if you use the same font type and the same color for the text to match the given design you can take this information from the Zeplin 🤩✨

- Kindly decrease the space here between the name of the book and the author and the category 🚀
- Kindly change the font type to be the same 🚀
- Kindly change the font color to match the design ♻

![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/c2810af3-ae09-4a89-88f4-24259dd1320c)

- Your
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/677d5a34-b196-4699-a31d-d4ee3d28ab3b)


- Given
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/e9a44fdb-a9f6-4f4a-91d2-706a3cf7232e)

2023-08-25 13:25 UTC, Reem-lab commented on src/components/Book.js
> +              <span>Completed</span>
- [ ] Amazing job so far but I think we need to make minor improvements to make our website the same as the given design so here it would be nice if you decrease the size  of the circle to make it like the given design ♻🚀

- [ ]  the number of percentages and the text completed it would be great if you decreased their font-weight smaller since in the Zeplin is smaller 🚀♻✨

- Your design
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/c2d96baf-ea48-4a55-8abe-23e6d49941b4)
  

- Given
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/5b3dd4ae-dc69-44a8-8041-3b01a88aaace)

2023-08-25 13:25 UTC, Reem-lab commented on src/components/Book.js
>        </div>
- [ ] Great job working on the styles so far but I think it would be great if you fix some issues here since I think in this part the spaces are different than the given design In [Zeplin](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378) so kindly make it smaller to match the given design ⬇🔥🚀🤩

- [ ]  I think it would be great if you use the same font type and the same color for the text to match the given design you can take this information from the Zeplin 🤩✨

- Kindly decrease the spaces here between the list for the last part ✨♻

- Your
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/b938cb81-0c0a-4282-b066-6952866e649f)


- Given
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/fcf8e7e3-27bf-40bd-ac92-8ca5a89417bd)

2023-08-25 13:25 UTC, Reem-lab commented on src/components/BookForm.js
> +            {status === 'pending' ? 'Adding...' : 'Add Book'}
- [ ] I think it would be great if you change the color of this text here since in your design is black but it is grey inZeplin design so kindly work on it to make it the same ✨✅🙏🏻

- Your
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/d9fd075a-5f15-4dd8-a3d9-4f08d42f9b02)


- Given
![image](https://github.com/Ochiengsteven/bookstore/assets/58553711/a4bb5033-494a-47e8-a78e-9ccf2662d5f9)

2023-08-26 18:16 UTC, rotimiazeez approved these changes
Hi @Ochiengsteven 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Good functioning App 👍🏽
* Good App UI 👍🏽
* Descriptive PR and README file 👍🏽
* All linter check passed 👍🏽

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 18:36 UTC, Ochiengsteven commented
Hi @rotimiazeez  you've approved the project but my dashboard is still showing review pending minutes later. What's the issue please. Because the deadline is almost up

2023-08-26 19:19 UTC, merged